version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

commands:
  nx-checks:
    steps:
      - nx/set-shas
      - run:
          name: Run nx affected:build
          command: npx nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --parallel
      - run:
          name: Run nx affected:lint
          command: npx nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD --parallel
      - run:
          name: Run nx affected:test
          command: npx nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --parallel

  nx-continue:
    steps:
      - run:
          name: Run continuation-parameters generator
          command: npx nx workspace-generator continuation-parameters --base=$NX_BASE --head=$NX_HEAD
      - when:
          condition: $CIRCLE_PULL_REQUEST
          steps:
            - continuation/continue:
                configuration_path: .circleci/continue.config.yml
                parameters: tmp/continuation-parameters.json
      - unless:
          condition: $CIRCLE_PULL_REQUEST
          steps:
            - continuation/finish

jobs:
  check-branch:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - nx-checks
      - nx-continue

  check-main:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - nx-checks
      - nx-continue

workflows:
  check:
    jobs:
      - check-branch:
          context:
            - ci-tool-secrets
          filters:
            branches:
              ignore:
                - main

      - check-main:
          context:
            - ci-tool-secrets
          filters:
            branches:
              only:
                - main
# version: 2.1

# setup: true

# orbs:
#   continuation: circleci/continuation@0.2.0
#   node: circleci/node@5.0.0
#   nx: nrwl/nx@1.1.3

# executors:
#   node-lts-browsers:
#     docker:
#       - image: cimg/node:16.14-browsers

# commands:
#   nx-checks:
#     steps:
#       - run:
#           name: Run affected:build
#           command: yarn nx affected --target=build --base=$NX_BASE --parallel
#       - run:
#           name: Run affected:lint
#           command: yarn nx affected --target=build --base=$NX_BASE --parallel
#       - run:
#           name: Run affected:test
#           command: yarn nx affected --target=test --base=$NX_BASE --parallel

# jobs:
#   checks:
#     executor: node-lts-browsers
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#       - nx/set-shas
#       - nx-checks
#       - persist_to_workspace:
#           root: '.'
#           paths: '.'

#   deploy-netlify:
#     executor: node-lts-browsers
#     steps:
#       - attach_workspace:
#           at: '.'
#       - run:
#           name: Run affected:deploy
#           command: yarn nx affected --target=deploy --base=$NX_BASE --parallel

# workflows:
#   check-branch:
#     jobs:
#       - checks:
#           context:
#             - ci-tool-secrets
#           filters:
#             branches:
#               ignore:
#                 - main
#                 - /^(pull\/).*$/
#       - deploy-netlify:
#           context:
#             - ci-tool-secrets
#           requires:
#             - checks

#   # check-pr:
#   #   jobs:
#   #     - checks:
#   #         context:
#   #           - ci-tool-secrets
#   #         filters:
#   #           branches:
#   #             only: /^(pull\/).*$/

#   # build-and-deploy:
#   #   jobs:
#   #     - checks:
#   #         context:
#   #           - ci-tool-secrets
#   #         filters:
#   #           branches:
#   #             only: main
