version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

commands:
  ci--setup:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - nx/set-shas

  nx--affected:
    parameters:
      target:
        type: string
      configuration:
        type: string
        default: ''
      parallel:
        type: integer
        default: 3
    steps:
      - when:
          condition: << parameters.configuration>>
          steps:
            - run:
                name: Run nx affected:<< parameters.target >>
                command: |
                  npx nx affected --base=$NX_BASE \
                                  --configuration=<< parameters.configuration >> \
                                  --head=$NX_HEAD \
                                  --parallel=<< parameters.parallel >> \
                                  --target=<< parameters.target >>
      - unless:
          condition: << parameters.configuration>>
          steps:
            - run:
                name: Run nx affected:<< parameters.target >>
                command: |
                  npx nx affected --base=$NX_BASE \
                                  --head=$NX_HEAD \
                                  --parallel=<< parameters.parallel >> \
                                  --target=<< parameters.target >>

  nx--checks:
    steps:
      - nx--affected:
          target: build
      - nx--affected:
          target: lint
      - nx--affected:
          target: test

jobs:
  main:
    executor:
      name: node/default
      tag: lts-browsers
    steps:
      - ci--setup
      - nx--checks
  pr:
    executor:
      name: node/default
      tag: lts-browsers
    steps:
      - ci--setup
      - nx--checks

workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main
      - pr:
          filters:
            branches:
              ignore: main
