version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

commands:
  nx--setup:
    - checkout
    - node/install-packages:
        pkg-manager: yarn
    - nx/set-shas

  nx--run-checks:
    steps:
      - run:
          name: Run nx affected:build
          command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
      - run:
          name: Run nx affected:lint
          command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run:
          name: Run nx affected:test
          command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3

jobs:
  main:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - checkout
      - nx--setup
      - nx--run-checks
  pr:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - checkout
      - nx--setup
      - nx--run-checks

workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main
      - pr:
          filters:
            branches:
              ignore: main
