version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

commands:
  nx--affected:
    parameters:
      target:
        type: string
      parallel:
        type: integer
        default: 3
    steps:
      - run:
          name: Run nx affected:<< parameters.target >>
          command: npx nx affected --target=<< parameters.target >> --base=$NX_BASE --head=$NX_HEAD --parallel=3

  nx--checks:
    steps:
      - nx--affected:
          target: build
      - nx--affected:
          target: lint
      - nx--affected:
          target: test

  nx--continue:
    parameters:
      pr:
        type: string
        default: ''
    steps:
      - run:
          name: Run continuation-parameters generator
          command: npx nx workspace-generator continuation-parameters --base=$NX_BASE --head=$NX_HEAD
      - when:
          condition: << parameters.pr >>
          steps:
            - continuation/continue:
                configuration_path: .circleci/continue.config.yml
                parameters: tmp/continuation-parameters.json
      - unless:
          condition: << parameters.pr >>
          steps:
            - continuation/finish

jobs:
  ci--setup:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: '.'
          paths: '.'

  check-branch:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - attach_workspace:
          at: '.'
      - nx--checks
      - nx--continue:
          pr: $CIRCLE_PULL_REQUEST

  check-main:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - attach_workspace:
          at: '.'
      - nx--checks
      - nx--continue:
          pr: $CIRCLE_PULL_REQUEST

workflows:
  setup_workflow:
    jobs:
      - ci--setup:
          name: setup

      - check-branch:
          context:
            - ci-tool-secrets
          requires:
            - setup
          filters:
            branches:
              ignore:
                - main

      - check-main:
          context:
            - ci-tool-secrets
          requires:
            - setup
          filters:
            branches:
              only:
                - main
