version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

executors:
  node-lts-browsers:
    docker:
      - image: cimg/node:16.14-browsers
    resource_class: small

jobs:
  checks:
    executor: node-lts-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - nx/set-shas
      - run:
          name: Run affected:build
          command: yarn nx affected --target=build --base=$NX_BASE --parallel
      - run:
          name: Run affected:lint
          command: yarn nx affected --target=build --base=$NX_BASE --parallel
      - run:
          name: Run affected:test
          command: yarn nx affected --target=test --base=$NX_BASE --parallel
      - persist_to_workspace:
          root: '.'
          paths: '.'

  deploy-netlify:
    executor: node-lts-browsers
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Run affected:deploy
          command: yarn nx affected --target=deploy --base=$NX_BASE --parallel

workflows:
  check-branch:
    jobs:
      - checks:
          context:
            - ci-tool-secrets
          filters:
            branches:
              ignore:
                - main
                - /^(pull\/).*$/
      - deploy-netlify:
          requires:
            - checks

  check-pr:
    jobs:
      - checks:
          context:
            - ci-tool-secrets
          filters:
            branches:
              only: /^(pull\/).*$/

  build-and-deploy:
    jobs:
      - checks:
          context:
            - ci-tool-secrets
          filters:
            branches:
              only: main
