version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

jobs:
  checks:
    docker:
      - image: cimg/node:14.17-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - nx/set-shas
      - run:
          name: Run affected:build
          command: yarn nx affected --target=build --base=$NX_BASE --parallel
      - run:
          name: Run affected:lint
          command: yarn nx affected --target=build --base=$NX_BASE --parallel
      - run:
          name: Run affected:test
          command: yarn nx affected --target=test --base=$NX_BASE --parallel

workflows:
  check-branch:
    jobs:
      - checks:
          filters:
            branches:
              ignore:
                - main
                - /^(pull\/).*$/

  check-pr:
    jobs:
      - checks:
          filters:
            branches:
              only: /^(pull\/).*$/

  build-and-deploy:
    jobs:
      - checks:
          filters:
            branches:
              only: main
