version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

parameters:
  kenniejaydavis-blog:
    type: boolean
    default: false

executor--node: &executor--node
  executor:
    name: node/default
    tag: 16.14-browsers

parameters--nx-run: &parameters--nx-run
  project:
    type: string
  configuration:
    type: string

commands:
  ci--attach-workspace:
    steps:
      - attach_workspace:
          at: '.'

  nx--run-checks:
    parameters:
      <<: *parameters--nx-run
    steps:
      - run:
          name: Execute nx run << parameters.project >>:build:<< parameters.configuration >>
          command: npx nx run << parameters.project >>:build:<< parameters.configuration >>
      - run:
          name: Execute nx run << parameters.project >>:lint
          command: npx nx run << parameters.project >>:lint
      - run:
          name: Execute nx run << parameters.project >>:test
          command: npx nx run << parameters.project >>:test

jobs:
  ci--setup:
    <<: *executor--node
    steps:
      - checkout
      - nx/set-shas
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: '.'
          paths: '.'

  nx--build:
    <<: *executor--node
    parameters:
      <<: *parameters--nx-run

    steps:
      - ci--attach-workspace
      - run:
          name: Execute nx run << parameters.project >>:build:<< parameters.configuration >>
          command: npx nx run << parameters.project >>:build:<< parameters.configuration >>

  nx--lint:
    <<: *executor--node
    parameters:
      <<: *parameters--nx-run
    steps:
      - ci--attach-workspace
      - run:
          name: Execute nx run << parameters.project >>:lint
          command: npx nx run << parameters.project >>:lint

  nx--test:
    <<: *executor--node
    parameters:
      <<: *parameters--nx-run
    steps:
      - ci--attach-workspace
      - run:
          name: Execute nx run << parameters.project >>:test
          command: npx nx run << parameters.project >>:test

  nx--netlify-deploy:
    <<: *executor--node
    parameters:
      <<: *parameters--nx-run
    steps:
      - ci--attach-workspace
      - run:
          name: Execute nx run << parameters.project >>:deploy:<< parameters.configuration >>
          command: npx nx run << parameters.project >>:deploy:<< parameters.configuration >>

workflows:
  kenniejaydavis-blog:
    when: << pipeline.parameters.kenniejaydavis-blog >>
    jobs:
      - ci--setup:
          name: setup
          context:
            - ci-tool-secrets
      - nx--build:
          name: build
          requires:
            - setup
          project: kenniejaydavis-blog
          configuration: development
      - nx--lint:
          name: lint
          requires:
            - setup
          project: kenniejaydavis-blog
          configuration: development
      - nx--test:
          name: test
          requires:
            - setup
          project: kenniejaydavis-blog
          configuration: development
      - nx--netlify-deploy:
          name: deploy pr
          context:
            - ci-tool-secrets
          requires:
            - setup
            - build
            - lint
            - test
          project: kenniejaydavis-blog
          configuration: development
          filters:
            branches:
              ignore:
                - main
