version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

parameters:
  kenniejaydavis-blog:
    type: boolean
    default: false

commands:
  ci--setup:
    steps:
      - checkout
      - nx/set-shas
      - node/install-packages:
          pkg-manager: yarn

  nx--run-checks:
    steps:
      - run:
          name: Run nx affected:build
          command: npx nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --parallel
      - run:
          name: Run nx affected:lint
          command: npx nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD --parallel
      - run:
          name: Run nx affected:test
          command: npx nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --parallel

jobs:
  netlify--deploy:
    executor:
      name: node/default
      tag: 16.14-browsers
    parameters:
      project:
        type: string
      configuration:
        type: string
    steps:
      - ci--setup
      - nx--run-checks
      - run:
          name: Execute nx run << parameters.project >>:deploy:<< parameters.configuration >>
          command: npx nx run << parameters.project >>:deploy:<< parameters.configuration >>

workflows:
  kenniejaydavis-blog:
    when: << pipeline.parameters.kenniejaydavis-blog >>
    jobs:
      - netlify--deploy:
          context:
            - ci-tool-secrets
          configuration: development
          project: kenniejaydavis-blog
          filters:
            branches:
              ignore:
                - main
