version: 2.1

orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3

parameters:
  kenniejaydavis-blog:
    type: boolean
    default: false

commands:
  nx-checks:
    steps:
      - nx/set-shas
      - run:
          name: Run nx affected:build
          command: npx nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --parallel
      - run:
          name: Run nx affected:lint
          command: npx nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD --parallel
      - run:
          name: Run nx affected:test
          command: npx nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --parallel

jobs:
  deploy-pr:
    executor:
      name: node/default
      tag: 16.14-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - nx-checks
      - run:
          name: Run affected:deploy
          command: yarn nx affected --target=deploy --base=$NX_BASE --head=$NX_HEAD --parallel

workflows:
  kenniejaydavis-blog:
    when: << pipeline.parameters.kenniejaydavis-blog >>
    jobs:
      - deploy-pr:
          context:
            - ci-tool-secrets
          filters:
            branches:
              ignore:
                - main
